name: build-test-worker-operator
on:
  pull_request:
    branches:
    - 'master'
    - 'release-*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2
        with:
          tags: worker-operator:latest
          push: false
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2
        with:
          file: test.Dockerfile
          tags: test-image:latest
          push: false
      - uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
        with:
          image: test-image:latest
          run: make test
